name: Deploy to azure

on:
    workflow_call:
        inputs:
            env:
                required: true
                type: string
            resource_group_name:
                required: true
                type: string
            app_service_name:
                required: true
                type: string
            app_service_slot_name:
                required: true
                type: string
        secrets:
            AZURE_CLIENT_ID: 
                required: true
            AZURE_TENANT_ID: 
                required: true
            AZURE_SUBSCRIPTION_ID: 
                required: true
jobs:
    deploy:
        name: Deploy ${{ inputs.env }}
        runs-on: ubuntu-latest
        environment: ${{ inputs.env }}

        steps:

             #This step here is to get access to the file "main.bicep" that is in this repo because we will use it later
             #If the file is not here or is outdated we will fail the "Run Bicep" Step that will come later.
            - name: Checkout repository
              uses: actions/checkout@v4 
            
            - name: download artifact
              uses: actions/download-artifact@v4
              with:
                name: dometrain-artifact
                path: artifacts/

            - name: Azure login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Run Bicep
              run: |
                  az deployment group create \
                    --name ${{ inputs.env }}-deployment-${{ github.run_number }} \
                    --template-file infrastructure/main.bicep \
                    --parameters infrastructure/environments/${{ inputs.env }}.bicepparam \
                    --resource-group ${{ inputs.resource_group_name }} \
                    --verbose
        
            - name: 'Deploy to Azure App Service Name'
              uses: azure/webapps-deploy@v2
              with: 
                app-name: app-dometrain-github-actions-fgavilan-${{ inputs.env }} 
                slot-name: myslot
                package: artifacts/

            - name: Swap slots
              run: |
                    az webapp deployment slot swap -g ${{ inputs.resource_group_name }} -n ${{ inputs.app_service_name }} --slot ${{ inputs.app_service_slot_name }} --target-slot production --verbose